# Generated by Django 5.2.14 on 2026-05-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('unit', models.CharField(choices=[('hour', 'Hour'), ('each', 'Each'), ('km', 'Kilometre')], default='hour', max_length=20)),
                ('price_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_code', models.CharField(choices=[('gst_free', 'GST-free'), ('taxable', 'Taxable')], default='gst_free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'item_number'],
            },
        ),
    ]
