# Generated by Django 5.2.14 on 2026-05-29 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participantworkerassignment'),
        ('scheduling', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('planned_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service_type', models.CharField(choices=[('community_access', 'Community access'), ('personal_care', 'Personal care'), ('domestic_assistance', 'Domestic assistance'), ('transport', 'Transport'), ('capacity_building', 'Capacity building'), ('other', 'Other')], max_length=40)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='draft', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='participants.participant')),
                ('support_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='scheduling.supportitem')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='workers.supportworker')),
            ],
            options={
                'ordering': ['service_date', 'start_time'],
            },
        ),
    ]
