# Generated by Django 5.2.14 on 2026-09-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='source',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled')], default='scheduled', max_length=20),
        ),
    ]
