# Generated by Django 5.2.14 on 2026-09-22 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participantworkerassignment'),
        ('scheduling', '0003_shift_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedMultiWorkerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('overlap_start_time', models.TimeField()),
                ('overlap_end_time', models.TimeField()),
                ('worker_count', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(choices=[('manual_handling', 'Manual handling'), ('behaviour_support', 'Behaviour support'), ('safety', 'Safety'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_multi_worker_supports', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_multi_worker_supports', to='participants.participant')),
                ('shifts', models.ManyToManyField(related_name='planned_multi_worker_supports', to='scheduling.shift')),
            ],
            options={
                'ordering': ['service_date', 'overlap_start_time', 'id'],
            },
        ),
    ]
