# Generated by Django 5.2.14 on 2026-09-28 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_plannedmultiworkersupport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('confirmed', 'Confirmed'), ('cancellation_review', 'Cancellation review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ParticipantCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_type', models.CharField(choices=[('short_notice', 'Short notice cancellation'), ('no_show', 'Participant did not attend')], max_length=20)),
                ('reason', models.CharField(choices=[('health', 'Health'), ('family', 'Family circumstances'), ('transport', 'Transport'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('previous_shift_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('confirmed', 'Confirmed'), ('cancellation_review', 'Cancellation review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], max_length=20)),
                ('claim_type', models.CharField(default='CANC', editable=False, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved for charging'), ('waived', 'Charge waived'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_participant_cancellations', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='participant_cancellation', to='scheduling.shift')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_participant_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
