# Generated by Django 5.2.14 on 2026-09-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('service_log_approved', 'Service log approved'), ('service_log_rejected', 'Service log rejected'), ('shift_cancelled', 'Shift cancelled'), ('invoice_created', 'Invoice created'), ('invoice_marked_issued', 'Invoice marked issued'), ('invoice_marked_paid', 'Invoice marked paid'), ('invoice_cancelled', 'Invoice cancelled'), ('invoice_deleted', 'Invoice deleted'), ('document_uploaded', 'Document uploaded'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('document_downloaded', 'Document downloaded')], max_length=50),
        ),
    ]
