# Generated by Django 5.2.14 on 2026-09-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('service_log_approved', 'Service log approved'), ('service_log_rejected', 'Service log rejected'), ('shift_cancelled', 'Shift cancelled'), ('invoice_created', 'Invoice created'), ('invoice_marked_issued', 'Invoice marked issued'), ('invoice_marked_paid', 'Invoice marked paid'), ('invoice_cancelled', 'Invoice cancelled'), ('invoice_deleted', 'Invoice deleted'), ('document_uploaded', 'Document uploaded'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('document_downloaded', 'Document downloaded'), ('support_coordinator_created', 'Support coordinator created'), ('support_coordinator_updated', 'Support coordinator updated'), ('participant_coordinator_assigned', 'Participant assigned to support coordinator'), ('coordination_log_submitted', 'Coordination log submitted'), ('coordination_log_approved', 'Coordination log approved'), ('coordination_log_rejected', 'Coordination log rejected')], max_length=50),
        ),
    ]
