# Generated by Django 5.2.14 on 2026-06-21 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Brisbane Star Care', max_length=120)),
                ('abn', models.CharField(default='36 601 940 023', max_length=30, verbose_name='ABN')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('bsb', models.CharField(blank=True, max_length=20, verbose_name='BSB')),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('invoice_prefix', models.CharField(default='BSC', max_length=12)),
                ('next_invoice_sequence', models.PositiveIntegerField(default=1)),
                ('accent_colour', models.CharField(default='#6f2c80', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, for example #6f2c80.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('logo', models.FileField(blank=True, upload_to='invoice_settings/logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice settings',
                'verbose_name_plural': 'Invoice settings',
            },
        ),
    ]
