# Generated by Django 5.2.14 on 2026-07-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoicesettings'),
        ('service_logs', '0002_servicelog_rejection_reason_servicelog_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('service', 'Service'), ('travel_non_labour', 'Provider travel - non-labour')], default='service', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='service_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='service_logs.servicelog'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('service_log', 'line_type'), name='unique_invoice_line_type_per_service_log'),
        ),
    ]
