# Generated by Django 5.2.14 on 2026-09-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0001_initial'),
        ('invoices', '0003_invoiceline_line_type_alter_invoiceline_service_log_and_more'),
        ('service_logs', '0003_servicelog_source_servicelog_unscheduled_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='unique_invoice_line_type_per_service_log',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('service', 'Service'), ('support_coordination', 'Support Coordination')], default='service', max_length=30),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='coordination_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='coordinators.coordinationlog'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('service', 'Service'), ('travel_non_labour', 'Provider travel - non-labour'), ('support_coordination', 'Support Coordination')], default='service', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='service_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='service_logs.servicelog'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(condition=models.Q(('service_log__isnull', False)), fields=('service_log', 'line_type'), name='unique_invoice_line_type_per_service_log'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(condition=models.Q(('coordination_log__isnull', False)), fields=('coordination_log',), name='unique_invoice_line_per_coordination_log'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coordination_log__isnull', True), ('service_log__isnull', False)), models.Q(('coordination_log__isnull', False), ('service_log__isnull', True)), _connector='OR'), name='invoice_line_has_exactly_one_source'),
        ),
    ]
