# Generated by Django 5.2.14 on 2026-09-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0002_alter_coordinationlog_status'),
        ('invoices', '0004_support_coordination_invoice'),
        ('scheduling', '0005_alter_shift_status_participantcancellation'),
        ('service_logs', '0003_servicelog_source_servicelog_unscheduled_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='invoice_line_has_exactly_one_source',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='participant_cancellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='scheduling.participantcancellation'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('service', 'Service'), ('cancellation', 'Participant cancellation'), ('travel_non_labour', 'Provider travel - non-labour'), ('support_coordination', 'Support Coordination')], default='service', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(condition=models.Q(('participant_cancellation__isnull', False)), fields=('participant_cancellation',), name='unique_invoice_line_per_participant_cancellation'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coordination_log__isnull', True), ('participant_cancellation__isnull', True), ('service_log__isnull', False)), models.Q(('coordination_log__isnull', False), ('participant_cancellation__isnull', True), ('service_log__isnull', True)), models.Q(('coordination_log__isnull', True), ('participant_cancellation__isnull', False), ('service_log__isnull', True)), _connector='OR'), name='invoice_line_has_exactly_one_source'),
        ),
    ]
