# Generated by Django 5.2.14 on 2026-10-05 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoiceline_invoice_line_has_exactly_one_source_and_more'),
        ('service_logs', '0003_servicelog_source_servicelog_unscheduled_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBillingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30)),
                ('original_values', models.JSONField()),
                ('billing_values', models.JSONField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_adjustments', to='invoices.invoice')),
                ('service_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_adjustments', to='service_logs.servicelog')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
