# Generated by Django 5.2.14 on 2026-09-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinationlog',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
