# Generated by Django 5.2.14 on 2026-10-03 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinators', '0002_alter_coordinationlog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinationLogChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('revision', 'Revised and resubmitted'), ('approval', 'Approved'), ('rejection', 'Rejected'), ('correction', 'Correction note'), ('billing_review', 'Invoice review required')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='coordinators.coordinationlog')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
