# Generated by Django 5.2.14 on 2026-09-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('support_worker', 'Support Worker'), ('support_coordinator', 'Support Coordinator'), ('accountant', 'Accountant')], max_length=30),
        ),
    ]
