# Generated by Django 5.2.14 on 2026-05-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ndis_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=4)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('plan_start_date', models.DateField(blank=True, null=True)),
                ('plan_end_date', models.DateField(blank=True, null=True)),
                ('management_type', models.CharField(blank=True, choices=[('ndia_managed', 'NDIA managed'), ('plan_managed', 'Plan managed'), ('self_managed', 'Self managed')], max_length=30)),
                ('plan_manager_name', models.CharField(blank=True, max_length=150)),
                ('plan_manager_email', models.EmailField(blank=True, max_length=254)),
                ('plan_manager_phone', models.CharField(blank=True, max_length=30)),
                ('support_coordinator_name', models.CharField(blank=True, max_length=150)),
                ('support_coordinator_email', models.EmailField(blank=True, max_length=254)),
                ('support_coordinator_phone', models.CharField(blank=True, max_length=30)),
                ('worker_visible_notes', models.TextField(blank=True)),
                ('address_access_instructions', models.TextField(blank=True)),
                ('risk_safety_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
