# Generated by Django 5.2.14 on 2026-05-28 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantWorkerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='participants.participant')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_assignments', to='workers.supportworker')),
            ],
            options={
                'ordering': ['-is_active', '-start_date', 'worker__last_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('participant', 'worker'), name='unique_active_participant_worker_assignment')],
            },
        ),
    ]
