# Generated by Django 5.2.14 on 2026-09-01 01:08

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='required_document_type',
            field=models.CharField(blank=True, choices=[('police_check', 'Police Check'), ('ndis_worker_screening', 'NDIS Worker Screening Check'), ('first_aid', 'First Aid Certificate'), ('cpr', 'CPR Certificate'), ('wwcc', 'Working With Children Check'), ('driver_licence', 'Driver Licence'), ('ndis_orientation', 'NDIS Worker Orientation Module'), ('resume', 'Resume'), ('visa', 'Visa Document'), ('qualification', 'Educational Qualification')], max_length=60),
        ),
        migrations.AddField(
            model_name='document',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_upload_path),
        ),
    ]
