# Generated by Django 5.2.14 on 2026-05-30 00:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0002_participantworkerassignment'),
        ('scheduling', '0002_shift'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('actual_start_time', models.TimeField()),
                ('actual_end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('actual_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kilometres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('case_notes', models.TextField()),
                ('worker_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('invoiced', 'Invoiced')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_logs', to='participants.participant')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_log', to='scheduling.shift')),
                ('support_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_logs', to='scheduling.supportitem')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_logs', to='workers.supportworker')),
            ],
            options={
                'ordering': ['-service_date', '-submitted_at'],
            },
        ),
    ]
