# Generated by Django 5.2.14 on 2026-09-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_logs', '0002_servicelog_rejection_reason_servicelog_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='source',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='unscheduled_reason',
            field=models.TextField(blank=True),
        ),
    ]
