# Generated by Django 5.2.14 on 2026-05-28 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('employee', 'Employee'), ('subcontractor', 'Subcontractor')], default='employee', max_length=30)),
                ('abn', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('police_check_status', models.CharField(choices=[('not_provided', 'Not provided'), ('pending', 'Pending'), ('current', 'Current'), ('expired', 'Expired')], default='not_provided', max_length=30)),
                ('police_check_expiry', models.DateField(blank=True, null=True)),
                ('wwcc_status', models.CharField(choices=[('not_provided', 'Not provided'), ('pending', 'Pending'), ('current', 'Current'), ('expired', 'Expired')], default='not_provided', max_length=30, verbose_name='WWCC / Blue Card status')),
                ('wwcc_expiry', models.DateField(blank=True, null=True, verbose_name='WWCC / Blue Card expiry')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
